// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBWOfla8DPkJrdXrUP0ZWdbC1JJmfO4Sk',
    appId: '1:500464066434:web:53a945f61f7ad44a72f99b',
    messagingSenderId: '500464066434',
    projectId: 'skripsi-79bf8',
    authDomain: 'skripsi-79bf8.firebaseapp.com',
    storageBucket: 'skripsi-79bf8.firebasestorage.app',
    measurementId: 'G-GBJLZS9FH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21dTb5_q9dJT80WzW0ZmJlbiP9TXcnkI',
    appId: '1:500464066434:android:7a76c3bb935a89f672f99b',
    messagingSenderId: '500464066434',
    projectId: 'skripsi-79bf8',
    storageBucket: 'skripsi-79bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrxQJNYFPKOHMaS4S20NCrVhuhLOvp3VU',
    appId: '1:500464066434:ios:203f7eb9d9b37a3672f99b',
    messagingSenderId: '500464066434',
    projectId: 'skripsi-79bf8',
    storageBucket: 'skripsi-79bf8.firebasestorage.app',
    iosBundleId: 'com.example.skripsi',
  );
}
